'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Namespace TaskManager.TaskDatabase
    Public NotInheritable Class ConnectionHelper

        Private Sub New()
        End Sub

        Public Const ConnectionString As String = "XpoProvider=MSSqlServer;data source=(local);integrated security=SSPI;initial catalog=TaskDatabase"
        Public Shared Sub Connect(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption)
            XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption)
            XpoDefault.Session = Nothing
        End Sub
        Public Shared Function GetConnectionProvider(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption) As DevExpress.Xpo.DB.IDataStore
            Return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption)
        End Function
        Public Shared Function GetConnectionProvider(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption, <System.Runtime.InteropServices.Out()> ByRef objectsToDisposeOnDisconnect() As IDisposable) As DevExpress.Xpo.DB.IDataStore
            Return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, objectsToDisposeOnDisconnect)
        End Function
        Public Shared Function GetDataLayer(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption) As IDataLayer
            Return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption)
        End Function
    End Class

End Namespace
