//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace TaskManager.TaskDatabase
{

    public partial class Person : XPLiteObject
    {
        int fPersonId;
        [Key(true)]
        public int PersonId
        {
            get { return fPersonId; }
            set { SetPropertyValue<int>("PersonId", ref fPersonId, value); }
        }
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>("Title", ref fTitle, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        string fCity;
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>("City", ref fCity, value); }
        }
        string fState;
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>("State", ref fState, value); }
        }
        string fZip;
        public string Zip
        {
            get { return fZip; }
            set { SetPropertyValue<string>("Zip", ref fZip, value); }
        }
        string fCountry;
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>("Country", ref fCountry, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>("BirthDate", ref fBirthDate, value); }
        }
        DateTime fHireDate;
        public DateTime HireDate
        {
            get { return fHireDate; }
            set { SetPropertyValue<DateTime>("HireDate", ref fHireDate, value); }
        }
        System.Drawing.Image fImage;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Image
        {
            get { return fImage; }
            set { SetPropertyValue<System.Drawing.Image>("Image", ref fImage, value); }
        }
        int fColor;
        public int Color
        {
            get { return fColor; }
            set { SetPropertyValue<int>("Color", ref fColor, value); }
        }
        [PersistentAlias("[FirstName] + ' ' + [LastName]")]
        public string Name
        {
            get { return (string)(EvaluateAlias("Name")); }
        }
        [Association(@"TaskReferencesPerson", typeof(Task))]
        public XPCollection<Task> Tasks { get { return GetCollection<Task>("Tasks"); } }
    }

}
